// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPd1h60MLSvmmzQapJCTn4WxPA99XVELM',
    appId: '1:48249761736:web:6892b0629b26ae15001afd',
    messagingSenderId: '48249761736',
    projectId: 'widgetshare-6a57b',
    authDomain: 'widgetshare-6a57b.firebaseapp.com',
    storageBucket: 'widgetshare-6a57b.firebasestorage.app',
    measurementId: 'G-ZPN9J3LS86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKa22jaeLa3aevl0_9VSXoKbhpiutJJh8',
    appId: '1:48249761736:android:fc5c712cb6d9e041001afd',
    messagingSenderId: '48249761736',
    projectId: 'widgetshare-6a57b',
    storageBucket: 'widgetshare-6a57b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtyODflpY937y13OLZbhgk4aDbZ5WOa1E',
    appId: '1:48249761736:ios:e5021fb75a973394001afd',
    messagingSenderId: '48249761736',
    projectId: 'widgetshare-6a57b',
    storageBucket: 'widgetshare-6a57b.firebasestorage.app',
    iosBundleId: 'com.example.widgetShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtyODflpY937y13OLZbhgk4aDbZ5WOa1E',
    appId: '1:48249761736:ios:e5021fb75a973394001afd',
    messagingSenderId: '48249761736',
    projectId: 'widgetshare-6a57b',
    storageBucket: 'widgetshare-6a57b.firebasestorage.app',
    iosBundleId: 'com.example.widgetShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPd1h60MLSvmmzQapJCTn4WxPA99XVELM',
    appId: '1:48249761736:web:b0b4a556bf114225001afd',
    messagingSenderId: '48249761736',
    projectId: 'widgetshare-6a57b',
    authDomain: 'widgetshare-6a57b.firebaseapp.com',
    storageBucket: 'widgetshare-6a57b.firebasestorage.app',
    measurementId: 'G-V8SYGFGZ2S',
  );
}
